# Default values for aks-store-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: "dev"

# Image registry configuration
imageRegistry: "" # ACR login server (e.g. myacr.azurecr.io)

# No need for ghcr pull secrets when using ACR
imagePullSecrets: []

useRabbitMQ: true # when true, local rabbitmq container will be used
useMongoDB:  true # when true, local mongodb container will be used

useAzureAd: false # when true, Azure AD auth will be used for ai-service, order-service, and makeline-service
managedIdentityName: "" # name of the Azure AD identity to use for the service account
managedIdentityClientId: "" # client ID of the managed identity to use for the service account

aiService:
  # Specifies whether a ai-service deployment and service should be created
  create: false
  modelDeploymentName: ""
  openAiEndpoint: ""
  openAiKey: ""
  openAiOrgId: ""
  useAzureOpenAi: false
  openAiDalleEndpoint: ""
  openAiDalleModelName: ""
  azureOpenAiApiVersion: "2024-02-15-preview"
  image:
    repository: "aks-store-demo/ai-service"
    tag: "latest"

orderService:
  queueHost: "rabbitmq"
  queuePort: "5672"
  queueUsername: "username"
  queuePassword: "password"
  queueName: "orders"
  queueTransport: ""
  image:
    repository: "aks-store-demo/order-service"
    tag: "latest"

makelineService:
  orderQueueUri: "amqp://rabbitmq:5672"
  orderQueueUsername: "username"
  orderQueuePassword: "password"
  orderQueueName: "orders"
  orderQueueHost: ""
  orderDBApi: "mongodb"
  orderDBUri: "mongodb://mongodb:27017"
  orderDBName: "orderdb"
  orderDBCollectionName: "orders"
  orderDBContainerName: "orders"
  orderDBUsername: ""
  orderDBPassword: ""
  image:
    repository: "aks-store-demo/makeline-service"
    tag: "latest"

productService:
  image:
    repository: "aks-store-demo/product-service"
    tag: "latest"

storeAdmin:
  image:
    repository: "aks-store-demo/store-admin"
    tag: "latest"
  serviceType: LoadBalancer

storeFront:
  image:
    repository: "aks-store-demo/store-front"
    tag: "latest"
  serviceType: LoadBalancer

virtualCustomer:
  image:
    repository: "aks-store-demo/virtual-customer"
    tag: "latest"

virtualWorker:
  image:
    repository: "aks-store-demo/virtual-worker"
    tag: "latest"

mongodb:
  image:
    repository: "library/mongo"
    tag: "4.2"

rabbitmq:
  image:
    repository: "library/rabbitmq"
    tag: "3.13-server"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}